### ISSUE TITLE
Upgrade of carbon and graphite-web leaves pip confused about version

### ISSUE THREAD

**Issue by olavmrk** [echocat/puppet-graphite#235]
After the default version of `carbon` & `graphite-web` was changed from 0.9.12 to 0.9.15 today, this module tried to upgrade these packages to 0.9.15 for every puppet run.

The reason for this is that after the successful install of the new version of the packages, `pip freeze` still shows the old version.

My guess is that the cause is the symlinks created during [installation](https://github.com/echocat/puppet-graphite/blob/v5.16.0/manifests/install.pp#L116). Manually deleting the `graphite_web-0.9.12-py2.7.egg-info` and `carbon-0.9.12-py2.7.egg-info` symlinks in `/usr/lib/python2.7/dist-packages` makes `pip freeze` show the correct versions.

**Comment by dwerder** [comment]
Won,t fix. Until someone send a PR if this is still an issue.

**Comment by bsmaldon** [comment]
This affected me too, seems as though pip can leave a directory `/opt/graphite/lib/carbon-0.9.12-p2.7.egg-info` laying around which then gets copied in by the exec resource in install.pp line 133
`      'carbon_hack' => {
        command => "ln -s \"${::graphite::base_dir_REAL}/lib/\"${carbon} \"${::graphite::params::libpath}/\""
}`
Patched the code to use `${::graphite::gr_carbon_ver}` which worked for me but I am not submitting a pull request because I realised that would fail if 'latest' were specified as the version. Would an exec statement calling `rm \"${::graphite::params::libpath}/carbon-*-py${::graphite::params::pyver}.egg-info\"` be bad practice? Is the `$carbon` variable on line 130 there just for readability?
