### ISSUE TITLE
CentOS 7 - No package 'python-tzlocal'

### ISSUE THREAD

**Issue by wershlak** [echocat/puppet-graphite#236]
The puppet learning VM installs this module but it looks like version 5.16.0 fails with CentOS 7 due to a lack of a python-tzlocal package.

Error: Execution of '/bin/yum -d 0 -e 0 -y install python-tzlocal' returned 1: Error: Nothing to do
Error: /Stage[main]/Graphite::Install/Package[python-tzlocal]/ensure: change from purged to present failed: Execution of '/bin/yum -d 0 -e 0 -y install python-tzlocal' re
turned 1: Error: Nothing to do

I reverted to 5.15.0 and it works.

**Comment by dwerder** [comment]
I see that there was an issue at https://tickets.puppetlabs.com/browse/LEARNVM-280
But it is closed. So I assume that the version is set sticked to version 5.15.0

**Comment by squarebracket** [comment]
The problem was that the learning VM was missing the EPEL repository, which is the only source for python-tz. The presence of the repository could be enforced by ensuring the [`epel-release` package](https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F), if that's something you want to do.

**Comment by dwerder** [comment]
README.md of this module recommends (see requierements) the use of the epel repo already.
