### ISSUE TITLE
[develop] Invalid relationship: Exec[fix graphite race condition] 

### ISSUE THREAD

**Issue by erikanderson** [echocat/puppet-graphite#245]
`Puppet 4.3.2, Puppetdb 3.2.3, Puppetserver 2.2.1`

I am testing out the `develop` branch and came across an error:

`
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Exec[fix graphite race condition] { require => Service[carbon-cache] }, because Service[carbon-cache] doesn't seem to be in the catalog
`

I'm going to take a look at it and possibly put up a PR to fix

**Comment by dwerder** [comment]
Any news here?

**Comment by squarebracket** [comment]
This one is my fault; when I made the fix for the race condition I didn't account for the gr_enable_carbon_cache setting. I've written a fix which involved a bit of reorganization of the code (moving the race condition fix from `config_*.pp` to `config.pp`), so I am doing a bit of local testing before I submit the PR.

**Comment by erikanderson** [comment]
@squarebracket @dwerder coming across this in the latest release 6.0.3 as well:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Exec[fix graphite race condition] { require => Service[carbon-cache] }, because Service[carbon-cache] doesn't seem to be in the catalog
```

**Comment by dwerder** [comment]
Maybe you want to try the develop branch, wich will be the next 6.1.0 release.

**Comment by squarebracket** [comment]
Unfortunately the bug was not fixed in #281 , as there's still no way for handling the race condition fix without the `require => Service['carbon-cache']` bit. When I tried to remove it, I got a bunch of ordering issues -- services coming up prematurely and stuff. I need to take a more in-depth look at the ordering of things so that I can shuffle around the metaparameters a bit to be independent from carbon-cache...

**Comment by squarebracket** [comment]
Ok, pretty sure I've fixed the problem you're seeing in PR #282. If you want to try it out before the next module release, you can download https://github.com/echocat/puppet-graphite/pull/282.patch to your `/opt/graphite` and `git apply 282.patch`.

**Comment by squarebracket** [comment]
@erikanderson does 6.0.4 fix the issue you were seeing?

**Comment by dwerder** [comment]
No response. So it will be closed.
