### ISSUE TITLE
Duplicate declaration: Package[python-ldap] is already declared

### ISSUE THREAD

**Issue by captnswing** [echocat/puppet-graphite#278]
My company's base puppet module already installs python-ldap. Since ldap is by default disabled, it would be nice to only install python-ldap when `gr_use_ldap = true`

I tried to override `$common_os_pkgs` in my yaml, leaving out `python-ldap` 

``` yaml
graphite::params::common_os_pkgs:
  - python-tz
  - python-memcache
  - python-mysqldb
  - python-psycopg2
  - python-simplejson
  - python-sqlite
```

... but to no avail

**Comment by dwerder** [comment]
This does not work, because common_os_pkgs is used as a scope variable and not as a class parameter. Thats my gues.

Your solution would be a good one. Do you want to send a PR against develop branch?

**Comment by captnswing** [comment]
I'm actually not sure how to do that.. my puppet-fu is quite limited :/

**Comment by captnswing** [comment]
On a more principle level, if the user doesn't want ldap (`gr_use_ldap =false`), python-ldap shouldn't be installed either - no?

**Comment by captnswing** [comment]
wouldn't it be enough to do
```
$common_os_pkgs = [
  'MySQL-python',
  'pyOpenSSL',
  'python-memcached',
  'python-psycopg2',
  'python-zope-interface',
  'python-tzlocal',
]

if $::gr_use_ldap {
  $common_os_pkgs = union($common_os_pkgs,['python-ldap'])
}
```
in `params.pp` (and adapt the spec tests of course)?

**Comment by dwerder** [comment]
That will not work, because params.pp is inherited and so it will be executed before the class, which inherits it. So $gr_use_ldap will properly not be set. A better way would be to get the "package code part" out of the params class. Because obviously that are no parameters, but definition, which should be done in the install class, where they are needed. And then your solution would work fine.
