### ISSUE TITLE
Carbon-cache can't be properly restarted/started if gr_storage_dir is specified

### ISSUE THREAD

**Issue by arymkus** [echocat/puppet-graphite#329]
That's a problem from carbon's config - PID_DIR said to inherit from STORAGE_DIR, but it doesn't.
The carbon's pid files are placed then into the default directory /opt/graphite/storage/ instead of one specified in gr_storage_dir module parameter.
The systemctl unit file is generated properly and expects pid files to be placed into gr_storage_dir, can't find them and kinda fails (carbon's are started) on puppet agent run. 
That fails the entire module and manifest apply.

Patch file is attached (zipped).
[fix_carbon_pid_dir_generation.zip](https://github.com/echocat/puppet-graphite/files/921789/fix_carbon_pid_dir_generation.zip)

**Comment by Ajedi32** [comment]
FYI, rather than sending a patch file as an attachment, you might want to consider submitting a pull request instead: https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project

That way everyone can see and comment inline on the full diff in GitHub's web UI, the project maintainer can merge your changes by simply clicking a button (instead of having to manually apply your patch), and the project's Continuous Integration system can automatically run the full test suite on your version of the repository to make sure everything is working properly.
