### ISSUE TITLE
Fresh install fails on CentOS 7.4 using Graphite v1.1.1 

### ISSUE THREAD

**Issue by jbehrends** [echocat/puppet-graphite#360]
On a brand new machine: 
CentOS 7.4
v7.3.0 of this module 
v1.1.1 of graphite

```
Notice: /Stage[main]/Graphite::Config/Exec[Initial django db creation]/returns: python: can't open file 'manage.py': [Errno 2] No such file or directory
Error: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Failed to call refresh: 'python manage.py syncdb --noinput' returned 2 instead of one of [0]
Error: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: 'python manage.py syncdb --noinput' returned 2 instead of one of [0]
```

It appears that "/opt/graphite/webapp/graphite/manage.py" no longer exists.

**Comment by dwerder** [comment]
The modules defaults are set for Graphite 0.9.x at the moment. You have to made some adjustments to use it with Graphite 1.x.

I have no 1.x version running, so I cant help you at the moment. But if you have a working config please post it. So it can be used as default for the next major release.

**Comment by jbehrends** [comment]
In my experiments yesterday I found there are a handful of changes in moving from 0.9.x to 1.x that are not really backwards compatible..  So unless we wanted to add lots of complex logic, the module would end up dropping support for 0.9.x and only support 1.x going forward.   Assuming that is the correct decision I could probably make some time to work on a PR in the next few weeks to start moving things to 1.x...

**Comment by dwerder** [comment]
That would be fine. The next major release should support 1.x

**Comment by KurtClearwater** [comment]
Also having issues upgrading from 0.9.x to 1.x via this module. We are seeing the same error and it would be amazing to be able to use this module to upgrade to the latest version of Graphite.

**Comment by bplunkert** [comment]
We are seeing the error above, but we were able to work around it and successfully upgrade using the following:
```
graphite::gr_carbon_ver: '1.1.2'
graphite::gr_django_ver: '1.9'
graphite::gr_django_tagging_ver: '0.4.6'
graphite::gr_graphite_ver: '1.1.2'
graphite::gr_whisper_ver: '1.1.2'
graphite::gr_twisted_ver: '13.2.0'
```

**Comment by KurtClearwater** [comment]
The above did not work for us (Ubuntu) and we still see the error listed in the main ticket on a new build or an upgrade.
```
Notice: /Stage[main]/Graphite::Config/Exec[Initial django db creation]/returns: python: can't open file 'manage.py': [Errno 2] No such file or directory
Error: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Failed to call refresh: python manage.py syncdb --noinput returned 2 instead of one of [0]
Error: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: python manage.py syncdb --noinput returned 2 instead of one of [0]
```

**Comment by fschaer** [comment]
Hi,

@KurtClearwater you apparently did not re-define `graphite::gr_django_init_command`

@bplunkert suggests using django 1.9, but it does not work for me and gives me python exceptions in my apache wsgi logs for graphite-web which would apparently require django-inspectdb : 

`AttributeError: 'module' object has no attribute 'getmro'`

@bplunkert also disables initial graphite db creation, which would prevent graphite-web startup/operation . And the django 1.9 did not work for that db creation until I tried django 1.11.

For me this worked as a fresh install and for upgrades : 

```
graphite::gr_django_init_command: bash -c 'PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb && chown apache:apache /data/graphite/storage/log/*.log /opt/graphite/storage/graphite.db'
graphite::gr_carbon_ver: '1.1.2'
graphite::gr_django_ver: '1.11'
graphite::gr_django_tagging_ver: '0.4.6'
graphite::gr_graphite_ver: '1.1.2'
graphite::gr_whisper_ver: '1.1.2'
graphite::gr_twisted_ver: '13.2.0'
```

I was forced to add a bash -c because the puppet exec would otherwise truncate after the PYTHONPATH statement
The chowns also are required - it would be better to run the initial db creation exec as apache though, that would be cleaner and would not require the chowns.


For an upgrade on another node, I had to kill carbon-cache which did not stop correctly and prevented the 1st puppet run to go on (port 7002 was in use), and then I faced already existing python egg-info symlinks

To fix that 2nd issue, I changed the gweb_hack and carbon_hack to "ln -sf" here : 
https://github.com/echocat/puppet-graphite/blob/cfe143df4a3572a5294691b9c543619f85813168/manifests/install.pp#L134
https://github.com/echocat/puppet-graphite/blob/cfe143df4a3572a5294691b9c543619f85813168/manifests/install.pp#L138

That's because the module apparently attempted to upgrade two packages on each puppet run : 
```
Notice: /Stage[main]/Graphite::Install/Package[django-tagging]/ensure: ensure changed '0.4.3' to '0.4.6'
Notice: /Stage[main]/Graphite::Install/Package[graphite-web]/ensure: ensure changed '0.9.15' to '1.1.2'
```

pip list effectively showed the old versions. Weird. a pip uninstall of these + a puppet run fixed it...

Finally (!), 

- my upgrades forced me to remove the existing graphite.db `/opt/graphite/storage/graphite.db` as the db initialization complained (I'm using grafana, so I didn't care too much)
- one upgrade failed because pip did not want to remove symlinks in /usr/lib/python2.7/site-packages, which I did manually

happy graphite 1.1.2 !
